version: '3'

services:
  oracle-db:
    dns: oracle-db
    image: oracleinanutshell/oracle-xe-11g:latest
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata
    environment:
      - ORACLE_SID=xe
      - ORACLE_PDB=mom
      - ORACLE_PWD=mom
    ports:
      - 1521:1521
  mom:
    container_name: mom
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle-db:1521/xe
      - SPRING_DATASOURCE_USERNAME=mom
      - SPRING_DATASOURCE_PASSWORD=mom