--liquibase formatted sql

--changeset tslino:5
--comment: Insert users in MOM.MOM_USER
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (1, 'ADMIN1', 'admin1', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (2, 'ADMIN2', 'admin2', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (3, 'EDITOR1', 'editor1', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (4, 'EDITOR2', 'editor2', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (5, 'REVIEWER1', 'reviewer1', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (6, 'REVIEWER2', 'reviewer2', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (7, 'VIEWER1', 'viewer1', '', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (8, 'VIEWER2', 'viewer2', '', 1);

--changeset tslino:6
--comment: Insert permitions in MOM.MOM_PERM
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (1, 'ADMIN', 1);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (2, 'ADMIN', 2);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (3, 'EDITOR', 3);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (4, 'EDITOR', 4);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (5, 'REVIEWER', 4);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (6, 'REVIEWER', 5);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (7, 'REVIEWER', 6);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (8, 'VIEWER', 7);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (9, 'VIEWER', 8);