--liquibase formatted sql

--changeset tslino:1
--comment: Create table MOM.MOM_USER
CREATE TABLE MOM.MOM_USER (
    COD_USER NUMBER(10) CONSTRAINT PK_MOM_USER_COD_USER PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) CONSTRAINT UK_MOM_USER_NAME UNIQUE,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ACTIVE NUMBER(1) NOT NULL
);

--changeset tslino:2
--comment: Create table MOM.MOM_PERM
CREATE TABLE MOM.MOM_PERM (
    COD_PERM NUMBER(10) CONSTRAINT PK_MOM_PERM_COD_PERM PRIMARY KEY,
    PERM VARCHAR(30) NOT NULL,
    COD_USER NUMBER(10) CONSTRAINT FK_MOM_PERM_COD_USER REFERENCES MOM_USER(COD_USER) NOT NULL
);

--changeset tslino:3
--comment: Create sequence MOM.MOM_SQ_USER
CREATE SEQUENCE MOM.MOM_SQ_USER INCREMENT BY 1 START WITH 9 MAXVALUE 9999999999 NOCYCLE;

--changeset tslino:4
--comment: Create sequence MOM.MOM_SQ_PERM
CREATE SEQUENCE MOM.MOM_SQ_PERM INCREMENT BY 1 START WITH 10 MAXVALUE 9999999999 NOCYCLE;

--changeset tslino:5
--comment: Insert users in MOM.MOM_USER
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (1, 'ADMIN1', 'admin1', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (2, 'ADMIN2', 'admin2', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (3, 'EDITOR1', 'editor1', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (4, 'EDITOR2', 'editor2', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (5, 'REVIEWER1', 'reviewer1', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (6, 'REVIEWER2', 'reviewer2', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (7, 'VIEWER1', 'viewer1', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);
INSERT INTO MOM.MOM_USER(COD_USER, NAME, USERNAME, PASSWORD, ACTIVE) VALUES (8, 'VIEWER2', 'viewer2', '$2a$10$l9BavzhTVCxjHzkN5Lcz0.ckfUQv1hgZJHmucSaibCfgE8KS0POGy', 1);

--changeset tslino:6
--comment: Insert permitions in MOM.MOM_PERM
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (1, 'ADMIN', 1);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (2, 'ADMIN', 2);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (3, 'EDITOR', 3);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (4, 'EDITOR', 4);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (5, 'REVIEWER', 4);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (6, 'REVIEWER', 5);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (7, 'REVIEWER', 6);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (8, 'VIEWER', 7);
INSERT INTO MOM.MOM_PERM(COD_PERM, PERM, COD_USER) VALUES (9, 'VIEWER', 8);